_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
                - 61
            "4": 3.12.7
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
